### PR TITLE
Remove unnecessary remote script sources from CSP

### PR DESCRIPTION
**Pull request by carbureted**
Will reduce risk score on https://crxcavator.io/report/affijhegklbkdinpepgphhlgphnhbenk/1.7.36

### CODE REVIEW

**Comment by carbureted** [comment]
Any chance this could get a look?

**Comment by hyperwidget** [comment]
ooh; my apologies, I didn't see the notification come through; I'll check it out - thanks!

**Comment by carbureted** [comment]
friendly ping

**Comment by carbureted** [comment]
ping

**Comment by carbureted** [comment]
👋

**Pull request merged**
