### PR TITLE
Enhancement: Facebook

### PR DESCRIPTION
**Pull request by turquoisemelon**
Hi Unbiasify team!

Here is the PR for adding Facebook to the chrome extension. 

# Issue - Enhancement ⭐️
issue: #6 

# Changes Introduced

- Add toggles and style rules for Facebook

# Screenshots
Here is what the news feed will look like:

facebook-news-feed

People search screen:

facebook-search-people

Here is what the user profile will look like:

facebook-user-profile

I haven't implemented style rules on the notifications and inbox screens, yet. Still, I wanted to put what I've done so far in here. Any feedback is welcome.

### CODE REVIEW

**Comment by bhavyata9** [comment]
Hey @turquoisemelon, it looks amazing so far!

**Comment by hyperwidget** [comment]
I'm actually totally fine with getting the conflicts resolved and us getting this into the code base

**Comment by turquoisemelon** [comment]
@hyperwidget Great! Will get the conflicts resolved as soon as I've got time

**Comment by hyperwidget** [comment]
Wonderful! Thanks so much for the helping hand

**Comment by turquoisemelon** [comment]
Just resolved the conflicts. Let me know if there's anything else that needs to be done before this gets in the code base. Happy to be of help!

**Pull request merged**
