### PR TITLE
Enhancements/Fixes

### PR DESCRIPTION
**Pull request by PR1YANKPAT3L**
Address issue #3 #41  LinkedIn Messaging now hides names/photos 
Address issue #7 Github now supported
Address issue #8 Meetup now supported
Address issue #47 #48 #49 
screenshot from 2018-06-26 01-32-22

### CODE REVIEW

**Comment by bhavyata9** [comment]
Pulled the code locally, and I don't think Github names are working. 
github-names

**Comment by PR1YANKPAT3L** [comment]
Made a commit for Github Profile names.

**Comment by hyperwidget** [comment]
I'm sorry I let this get so stale - I really want to thank you for your contributions to project this is great.

For future contributions, I'd suggest disabling your autoformatters if they don't match the existing format in the code to avoid massive diffs. I'll look through this and hopefully we'll get it in and life this week.

**Comment by hyperwidget** [comment]
I really want to thank you for all this work once again; this is all wonderful stuff 🙌

If you choose to help the project out in the future, it'd be great to have separate prs for each ticket, but this was great! Thanks again!

**Pull request merged**
