### PR TITLE
Tweak the order of display

### LINKED ISSUE #68: Reorder toggles
Right now the toggles in the menu are a little out of line with the target use cases for most users of the app - HRProfessionals

We should reorder our toggles to have the HRD related services nearer to the top:
The more HR related services include:
* Linkedin
* Greenhouse
* Lever

@1hauck are there any other services that we _currently_ cover that you'd suggest hoisting to the top of the list as well?

### PR DESCRIPTION
**Pull request by Aditya-Kolla**
Fixed #68 
Sorry about the previous file changes :sweat_smile:

### CODE REVIEW

**Comment by hyperwidget** [comment]
You should probably pull the latest version of master and rebase this branch - as is, the PR looks like you're updating the email in this PR too

**Comment by Aditya-Kolla** [comment]
Yeah, my bad. Do you want me to do another PR?

**Comment by hyperwidget** [comment]
Nah, we don't need a new PR; but you can update your branch on your side and push and it will update this PR

**Comment by Aditya-Kolla** [comment]
I tried to do what you said. Pretty new to git and github lemme know if anything's wrong. Sorry.

**Comment by hyperwidget** [comment]
There's nothing to apologize for! We're all new to things at some time :D

You nailed it!

**Comment by hyperwidget** [comment]
Thanks a million, super appreciated!

**Pull request merged**
